### ISSUE TITLE
Add support to pass hash method as an argument in code

### ISSUE THREAD

**Issue by pareek-narendra** [pareek-narendra/pkce#3]
Right now the pkce will be generated using SHA256, add option to pass the hash method name as an argument.

**Comment by ashish8947** [comment]
Hi @pareek-narendra, Can I work on the same?

**Comment by pareek-narendra** [comment]
@ashish8947 Great, assigning to you.

**Comment by ashish8947** [comment]
I have raised a pr #11 please have a look
