### ISSUE TITLE
Add support with your fav hash algorithm

### ISSUE THREAD

**Issue by pareek-narendra** [pareek-narendra/pkce#4]
Right now the code is in go lang and only support SHA256, add more algorithms support on a parameter basis.

**Comment by mayankagwl** [comment]
@pareek-narendra I like to work on the algorithm for hecktoberfest , please assign me

**Comment by pareek-narendra** [comment]
@mayankagwl Yeah, Thanks for contributing. I've Assigned the issue to you.

**Comment by mayankagwl** [comment]
@pareek-narendra  Raised PR for this issue
https://github.com/pareek-narendra/pkce/pull/9

**Comment by pareek-narendra** [comment]
Thanks @mayankagwl 
This is under review
